apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanagement-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmanagement-app
  template:
    metadata:
      labels:
        app: bookmanagement-app
    spec:
      containers:
      - name: book-app-container
        image: sainiharika/bookmanagement-app:latest # Use your private repository name
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: my-registry-secret # Reference the secret created for Docker Hub

---

apiVersion: v1
kind: Service
metadata:
  name: bookmanagement-app-service
spec:
  type: NodePort  # Change to LoadBalancer if using cloud or ClusterIP for internal access
  selector:
    app: bookmanagement-app
  ports:
    - protocol: TCP
      port: 8081       # Port for external access
      targetPort: 8081 # Port on the container
      nodePort: 30081  # Port on the node (only for NodePort type)
